### ISSUE TITLE
Outdated oled_task_user code

### ISSUE THREAD

**Issue by bax09** [Rwarcards762/lily58_bongocat#4]
OLED task function changed to be boolean https://github.com/qmk/qmk_firmware/pull/14864
Yet the keymap is still using "void oled_task_user(void)"
Compiling puts out an error

**Comment by Rwarcards762** [comment]
Thanks for pointing this out! I haven't recompiled this code in a while so I haven't seen that.

Looking into the QMK docs it's hard to see this change other than via the examples. It looks as though now instead of a `void` it is a `bool` that just `return False` at the end. If you have made those changes and can confirm they work, feel free to open an MR with the fix and I'll test it this weekend. 

Otherwise I'll try and get around to testing that the fix works this weekend and commit the change myself.

**Comment by Rwarcards762** [comment]
Didn't end up getting to it this past weekend -- I'll see about getting to it soon when I get the chance to bring my board home.

**Comment by Rwarcards762** [comment]
Fixed with merge, thanks @MinXuann :)
